# Generated by Django 3.1.1 on 2020-09-09 18:08

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc',
            field=models.FileField(upload_to=main.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='upload',
            name='hash',
            field=models.CharField(db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='upload',
            name='hash_secure',
            field=models.CharField(blank=True, db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='upload',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
